GET http://localhost:3001/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjkxZGE2NDllY2M0NDI4M2M0OTEzN2QiLCJpYXQiOjE2MDMzOTQxNDgsImV4cCI6MTYwMzQ4MDU0OH0.JpXXBLVom85YewDA8SqE9krinHPzaMtRhkJQtdZHYK8
###

POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
  "email": "tess1@gmail.com",
  "password": "password",
  "fullName": "test"
}
###

POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
  "email": "tess@gmail.com",
  "password": "password"
}
###

POST http://localhost:3001/api/auth/tokens
Content-Type: application/json

{
  "refreshToken": "ff1fca5bb0e9d4c41384df083582515fcfa5ba6ad6c2b3f0a5c26706e49e7634cdbf316c00cca7aa23fb67b4420adc675723816c122af0d471c921f78bda1196585a9a2e5ab92dd6e90d32784409001548f79a17019db80ef5ea13416399928b91998a7ae637d75e2a70f658214c6da56be6c8fb62379a8b"
}
###

PUT http://localhost:3001/api/users
Content-Type: application/json
Authorization: Bearer <insert token here>

{
  "_id": "5f901ffdeb35642320b3f8f5",
  "userData": {
    "email": "test@mail.com"
  }
}
###
